export type TicketEmailInput={firstName?:string|undefined;eventName:string;eventDate:string;venue:string;total:number;summary:string[];accessUrl:string;tickets:Array<{type:string;position:string;publicCode:string;url:string}>};
const esc=(value:string)=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
export const ticketEmailSubject='Tus entradas para Fiesta de Disfraces están listas';
export function renderTicketEmail(input:TicketEmailInput){
  const tickets=input.tickets.map(ticket=>`<tr><td style="padding:0 24px 18px"><table role="presentation" width="100%" style="border-collapse:collapse;border:1px solid #645f55;background:#11110f"><tr><td style="padding:22px"><div style="color:#f21d18;font:bold 12px Arial,sans-serif;letter-spacing:2px">VALID</div><h3 style="margin:8px 0 4px;color:#f4ead7;font:900 28px Arial,sans-serif">${esc(ticket.type)}</h3><p style="margin:0 0 16px;color:#d7cbb7;font:15px Arial,sans-serif">${esc(ticket.position)}</p><p style="margin:0 0 18px;color:#f4c430;font:12px monospace;overflow-wrap:anywhere">${esc(ticket.publicCode)}</p><a href="${esc(ticket.url)}" style="display:inline-block;background:#f4ead7;color:#090908;padding:13px 18px;text-decoration:none;font:bold 13px Arial,sans-serif;letter-spacing:1px">VER ENTRADA</a></td></tr></table></td></tr>`).join('');
  const greeting=input.firstName?`<p style="margin:0 0 10px;color:#f4ead7;font:18px Arial,sans-serif">Hola, ${esc(input.firstName)}.</p>`:'';
  const html=`<!doctype html><html><body style="margin:0;background:#ece7dc"><table role="presentation" width="100%" style="border-collapse:collapse;background:#ece7dc"><tr><td align="center" style="padding:24px 10px"><table role="presentation" width="600" style="width:100%;max-width:600px;border-collapse:collapse;background:#090908"><tr><td style="padding:28px 24px 20px;color:#f4ead7"><div style="font:bold 16px Arial,sans-serif;letter-spacing:4px">FEST-ON <span style="color:#f4c430">31 · 10 · 26</span></div><h1 style="margin:28px 0 12px;color:#f4ead7;font:900 46px/0.9 Arial,sans-serif">FIESTA DE<br><span style="color:#f21d18">DISFRACES</span></h1><p style="margin:0;color:#d7cbb7;font:bold 13px Arial,sans-serif;letter-spacing:1px">LA HACIENDA RIVIERA MAYA</p></td></tr><tr><td style="padding:24px;background:#151512">${greeting}<h2 style="margin:0 0 16px;color:#f4ead7;font:900 34px/0.95 Arial,sans-serif">TUS ENTRADAS<br><span style="color:#f21d18">ESTÁN LISTAS</span></h2><p style="margin:0 0 22px;color:#d7cbb7;font:16px/1.5 Arial,sans-serif">Compra confirmada. Tu pago fue confirmado y tus entradas para ${esc(input.eventName)} ya están listas.</p><table role="presentation" width="100%" style="border-collapse:collapse;border-top:1px solid #645f55;border-bottom:1px solid #645f55"><tr><td style="padding:16px 0;color:#f4ead7;font:bold 13px Arial,sans-serif">${esc(input.eventDate)}<br>${esc(input.venue)}</td><td align="right" style="padding:16px 0;color:#f4c430;font:bold 20px Arial,sans-serif">${input.total} ENTRADAS</td></tr></table><p style="margin:18px 0 0;color:#f4ead7;font:bold 15px Arial,sans-serif">${input.summary.map(esc).join(' · ')}</p><a href="${esc(input.accessUrl)}" style="display:block;margin-top:22px;background:#f21d18;color:#fff;padding:16px;text-align:center;text-decoration:none;font:bold 14px Arial,sans-serif;letter-spacing:1px">VER MIS ENTRADAS</a></td></tr>${tickets}<tr><td style="padding:24px;color:#d7cbb7;font:14px/1.5 Arial,sans-serif;border-top:1px solid #645f55"><strong style="color:#f4ead7">¿NECESITÁS AYUDA?</strong><br>Respondé este correo y el equipo de Fest-On te ayuda.<br><br><span style="font-size:11px">Ticketing &amp; technology by Programita</span></td></tr></table></td></tr></table></body></html>`;
  const lines=['FEST-ON','TUS ENTRADAS ESTÁN LISTAS','Compra confirmada.',input.firstName?`Hola, ${input.firstName}.`:'',`${input.eventName} — ${input.eventDate} — ${input.venue}`,`${input.total} ENTRADAS`,...input.summary,'',...input.tickets.flatMap(ticket=>[`${ticket.type} — ${ticket.position}`,ticket.publicCode,`VER ENTRADA: ${ticket.url}`]),'',`VER MIS ENTRADAS: ${input.accessUrl}`,'','¿NECESITÁS AYUDA?','Respondé este correo y el equipo de Fest-On te ayuda.','Ticketing & technology by Programita'];
  return {html,text:lines.filter(Boolean).join('\n')};
}
