import{describe,expect,it,vi}from'vitest';
import{maskEmail,parseOperatorArgs,runOperatorCommand}from'../../scripts/send-order-tickets-email';
const org='11111111-1111-4111-8111-111111111111',order='22222222-2222-4222-8222-222222222222';
const summary={organizationId:org,orderPublicCode:'ORD_public_reference',orderStatus:'paid',paymentStatus:'paid',ticketCount:3,ticketTypes:['1 HOMBRES','2 MUJERES'],destination:'buyer@example.test',deliveryStatus:'none'};
describe('controlled ticket email operator command',()=>{
 it('is dry-run by default and never calls the delivery service',async()=>{const send=vi.fn();const lines:string[]=[];await expect(runOperatorCommand(['--organization',org,'--order',order],{inspect:async()=>summary,send,log:line=>lines.push(line)})).resolves.toEqual({status:'dry_run'});expect(send).not.toHaveBeenCalled();expect(lines.join('\n')).toContain('Resend was not called');expect(lines.join('\n')).toContain('b***@example.test');expect(lines.join('\n')).not.toContain('buyer@example.test')});
 it('requires explicit --send and invokes the existing service once for one order',async()=>{const send=vi.fn(async()=>({status:'sent'}));await expect(runOperatorCommand(['--organization',org,'--order',order,'--send'],{inspect:async()=>summary,send,log:()=>{}})).resolves.toEqual({status:'sent'});expect(send).toHaveBeenCalledOnce();expect(send).toHaveBeenCalledWith(org,order)});
 it('rejects recipient overrides, multiple orders and malformed identifiers',()=>{expect(()=>parseOperatorArgs(['--organization',org,'--order',order,'--to','attacker@example.test'])).toThrow('Unsupported argument');expect(()=>parseOperatorArgs(['--organization',org,'--order',order,'--order',org])).toThrow();expect(()=>parseOperatorArgs(['--organization','bad','--order',order])).toThrow()});
 it('reports already_sent without exposing secrets',async()=>{const log=vi.fn();await expect(runOperatorCommand(['--organization',org,'--order',order,'--send'],{inspect:async()=>({...summary,deliveryStatus:'sent'}),send:async()=>({status:'already_sent'}),log})).resolves.toEqual({status:'already_sent'});const output=log.mock.calls.flat().join('\n');expect(output).toContain('already_sent');expect(output).not.toMatch(/RESEND_API_KEY|TICKET_QR_SECRET|sk_test_|re_/)});
 it('masks destinations',()=>expect(maskEmail('alex@example.com')).toBe('a***@example.com'));
 it('accepts one explicit operator target from environment',()=>{const previousOrg=process.env.EMAIL_DELIVERY_ORGANIZATION_ID,previousOrder=process.env.EMAIL_DELIVERY_ORDER_ID;process.env.EMAIL_DELIVERY_ORGANIZATION_ID=org;process.env.EMAIL_DELIVERY_ORDER_ID=order;try{expect(parseOperatorArgs([])).toEqual({organizationId:org,orderId:order,send:false})}finally{if(previousOrg===undefined)delete process.env.EMAIL_DELIVERY_ORGANIZATION_ID;else process.env.EMAIL_DELIVERY_ORGANIZATION_ID=previousOrg;if(previousOrder===undefined)delete process.env.EMAIL_DELIVERY_ORDER_ID;else process.env.EMAIL_DELIVERY_ORDER_ID=previousOrder}});
});
