import{afterEach,beforeEach,describe,expect,it}from'vitest';import{readFileSync}from'node:fs';
import{emailTicketAccessUrl,issueEmailTicketAccess,verifyEmailTicketAccess}from'../../apps/web/lib/email-ticket-access';
import{renderTicketEmail,ticketEmailSubject}from'../../apps/web/lib/ticket-email-template';
const order='22222222-2222-4222-8222-222222222222',org='11111111-1111-4111-8111-111111111111';
describe('Fest-On ticket email experience',()=>{const originalPublicUrl=process.env.PUBLIC_APP_URL,originalAppUrl=process.env.APP_URL,originalHost=process.env.HOST;beforeEach(()=>{process.env.TICKET_QR_SECRET='test-ticket-secret-that-is-long-enough-for-hmac';process.env.PUBLIC_APP_URL='https://tickets.example.test'});afterEach(()=>{if(originalPublicUrl===undefined)delete process.env.PUBLIC_APP_URL;else process.env.PUBLIC_APP_URL=originalPublicUrl;if(originalAppUrl===undefined)delete process.env.APP_URL;else process.env.APP_URL=originalAppUrl;if(originalHost===undefined)delete process.env.HOST;else process.env.HOST=originalHost});
 it('uses an encrypted read-only cross-device capability scoped to one order',()=>{const expiry=Date.now()+60_000;const token=issueEmailTicketAccess(org,order,expiry);const tampered=`${token.slice(0,20)}${token[20]==='A'?'B':'A'}${token.slice(21)}`;expect(token).not.toContain(order);expect(verifyEmailTicketAccess(token)).toMatchObject({organizationId:org,orderId:order,expiresAt:expiry});expect(verifyEmailTicketAccess(tampered)).toBeNull();expect(verifyEmailTicketAccess(issueEmailTicketAccess(org,order,Date.now()-1))).toBeNull();const url=emailTicketAccessUrl(org,order,expiry);expect(url).toBe(emailTicketAccessUrl(org,order,expiry));expect(url).toMatch(/^https:\/\/tickets\.example\.test\/entradas\/fse1_/);process.env.APP_URL='http://localhost:3000';process.env.HOST='attacker.example';expect(emailTicketAccessUrl(org,order,expiry)).toBe(url);delete process.env.PUBLIC_APP_URL;expect(()=>emailTicketAccessUrl(org,order,expiry)).toThrow('PUBLIC_APP_URL is required')});
 it('renders premium HTML and plain text with three unique ticket links and no internal or Stripe identifiers',()=>{const input={firstName:'Alex',eventName:'Fiesta de Disfraces',eventDate:'31 DE OCTUBRE DE 2026',venue:'LA HACIENDA RIVIERA MAYA',total:3,summary:['1 HOMBRE','2 MUJERES'],accessUrl:'https://tickets.example.test/entradas/safe',tickets:[{type:'HOMBRES',position:'Entrada 1 de 1',publicCode:'TKT_A',url:'https://tickets.example.test/t/a'},{type:'MUJERES',position:'Entrada 1 de 2',publicCode:'TKT_B',url:'https://tickets.example.test/t/b'},{type:'MUJERES',position:'Entrada 2 de 2',publicCode:'TKT_C',url:'https://tickets.example.test/t/c'}]};const rendered=renderTicketEmail(input);expect(ticketEmailSubject).toBe('Tus entradas para Fiesta de Disfraces están listas');expect((rendered.html.match(/VER ENTRADA</g)??[])).toHaveLength(3);for(const ticket of input.tickets){expect(rendered.html).toContain(ticket.url);expect(rendered.text).toContain(ticket.url)}expect(rendered.html).toContain('1 HOMBRE · 2 MUJERES');expect(rendered.text).toContain(input.accessUrl);expect(rendered.html+rendered.text).not.toMatch(/pi_|payment_intent|22222222-2222/)});
 it('keeps the email access route read-only and separate from payment capabilities',()=>{const page=readFileSync('apps/web/app/entradas/[capability]/page.tsx','utf8');expect(page).toContain('verifyEmailTicketAccess');expect(page).not.toMatch(/payments|\.insert\(|\.update\(|check_ins|verifyPaymentCapability/)});
});
